footprint: [[-0.085, -0.20], [-0.085, 0.2],[0.315, 0.2], [0.315, -0.2]]
robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
resolution: 0.05
obstacle_range: 3.0
raytrace_range: 3.0

static_layer:
  enabled: true
  map_topic: "/map"

obstacle_layer:
  enabled:              true
  max_obstacle_height:  1.2
  min_obstacle_height:  0.0
  # combination_method:   1
  obstacle_range: 2.0
  raytrace_range: 5.0
  inflation_radius: 0.30
  combination_method: 1
  observation_sources: laser_scan_sensor  camera_depth
  # track_unknown_space:  true    #true needed for disabling global path planning through unknown space

  laser_scan_sensor_2:
    data_type: LaserScan
    topic: /scan_2
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.01
    max_obstacle_height: 0.1

  sonar_scan_sensor:
    data_type: PointCloud2
    topic: /sonar_cloudpoint
    marking: true
    clearing: true
    min_obstacle_height: 0.11
    max_obstacle_height: 0.2
    observation_persistence: 0.0

  laser_scan_sensor:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.21
    max_obstacle_height: 0.30


  other_sensor_data:
    data_type: PointCloud
    topic: /other_sensor_data 
    marking: ture
    clearing: true
    min_obstacle_height: 0.31
    max_obstacle_height: 0.4

  camera_depth:
    data_type: PointCloud2
    topic: /camera/depth/points #_filtered
    marking: ture
    clearing: true
    min_obstacle_height: 0.41
    max_obstacle_height: 2.0

virtualWall_layer:
  enabled:              true
  topic:  "/virtualWall_cloudPoint"
  map_topic:            "/map"

sonar_layer:
  enabled:            true
  clear_threshold:    0.2
  mark_threshold:     0.8
  topics: ["/sonar0", "/sonar1", "/sonar2", "/sonar3", "/sonar4"]
  clear_on_max_reading: true

inlation_layer:
  enabled: true
  cost_scaling_factor: 10.0 #Previous 15.0
  inflation_radius: 0.25 #Previous 0.20
